# Generated by Django 2.0 on 2018-12-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mobile_model',
            field=models.CharField(default='小米', max_length=200, verbose_name='型号'),
        ),
    ]
