# Generated by Django 2.0 on 2018-12-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181204_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='闲置'),
            preserve_default=False,
        ),
    ]
