# Generated by Django 2.0 on 2018-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.CharField(choices=[('1', '应用开发部—测试组'), ('2', '应用开发部—开发组')], default='', max_length=50, verbose_name='责任人部门'),
            preserve_default=False,
        ),
    ]
