# Generated by Django 2.0 on 2018-12-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.CharField(max_length=6, verbose_name='责任人'),
        ),
    ]
