# Generated by Django 2.0 on 2018-12-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181204_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='serve_time',
            field=models.DateField(auto_now_add=True, default='2018-12-04', verbose_name='服役时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='email_text',
            field=models.EmailField(max_length=254, verbose_name='责任人邮箱'),
        ),
    ]
