# Generated by Django 2.0 on 2020-01-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_question_serve_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='department',
            field=models.CharField(choices=[('1', '应用开发部—测试组'), ('2', '应用开发部—开发组'), ('3', '其他部门')], max_length=50, verbose_name='责任人部门'),
        ),
    ]
